name = "ark-ds"
main = "worker.js"
compatibility_date = "2024-03-21"

# Configure environment variables
[vars]
# These are example values - replace with your actual keys
CLIENT_API_KEY = "your-client-api-key"
OPENAI_API_KEY = "your-openai-api-key"

# Specify route to Cloudflare Worker
# routes = ["https://your-worker-subdomain.yourdomain.com/*"]

# Specify route to Worker at your Cloudflare Pages custom domain
# routes = ["https://study-hard.pages.dev/api/*"]

# Or, just use the workers.dev subdomain during development:
workers_dev = true 
