name = "ark-ds"
main = "worker.js"
compatibility_date = "2024-03-21"

# Production environment variables
# Set these in Cloudflare Dashboard or using wrangler secrets
# Required environment variables:
# - CLIENT_API_KEY
# - API_BASE_URL
# - MODEL

# Specify route to Worker at your Cloudflare Pages custom domain
# routes = ["https://study-hard.pages.dev/api/*"]

# Or, just use the workers.dev subdomain during development:
workers_dev = true 
